application: metaboscribe
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js
  
- url: /font-awesome
  static_dir: static/font-awesome
  
- url: /.*
  script: metaboscribe.application
  secure: always
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
